Feat/pop 34 convert error code
poporonnet/kcms pull request #12
Opened 2023-12-21 05:19 UTC by C4N4242

issue POP-34 on Linear

2024-02-29 12:33 UTC, laminne requested changes

2024-02-29 12:33 UTC, laminne commented on src/entry/adaptor/errors.ts
> +function errorToCode(error: Error): string {
```suggestion
export function errorToCode(error: Error): string {
```
こうした方が良いかと

2024-03-11 22:59 UTC, laminne requested changes
errToCodeが`main.ts`で使われていない状態なので、エラーを返す部分で呼び出すようにしてください

2024-03-12 13:54 UTC, laminne requested changes

2024-03-12 13:54 UTC, laminne commented on tsconfig.json
> +    "allowImportingTsExtensions": true
謎の差分入ってるのでL23を消してください

2024-03-12 13:56 UTC, C4N4242 commented on tsconfig.json
> +    "allowImportingTsExtensions": true
これがないと.tsのファイルをimportできないので意図して追加してます

2024-03-12 13:59 UTC, laminne requested changes

2024-03-12 13:59 UTC, laminne commented on src/entry/main.ts
> +import { errorToCode } from './adaptor/errors.ts';
```suggestion
import { errorToCode } from './adaptor/errors.js';
```

2024-03-12 14:07 UTC, laminne approved these changes

2024-03-12 14:07 UTC, merged